language: r
sudo: false
cache: packages

install:
- Rscript -e 'install.packages(c("Rcpp","RNifti","testthat","jsonlite"))'

script:
- R CMD build .
- R CMD check *tar.gz
- R CMD INSTALL *tar.gz
- Rscript dcm_qa.R
